### ISSUE TITLE
BUG: Schemr Gets Stuck on Old Schemes

### ISSUE THREAD

**Issue by bcrotty** [benweier/Schemr#29]
There are certain color schemes that Schemr will not go past. I can still go to a previous scheme from there, but it goes back 2 schemes instead of the one immediately previous. When you use the keybind or menu item for next on these certain schemes, however, it just stays put. The schemes that this happens on don't seem to change the visible colors at all.

Here are some that I've found this to happen on:
- Packages/Material Theme/schemes/OLD/Material-Theme.tmTheme
- Packages/Material Theme/schemes/OLD/Material-Theme-Darker.tmTheme
- Packages/Material Theme/schemes/OLD/Material-Theme-Lighter.tmTheme
- Packages/Tomorrow Color Schemes/Tomorrow-Night.tmTheme
- Packages/Dracula Color Scheme/visual-studio-code/theme-dracula/themes/Dracula.tmTheme

The only way I can get past these schemes is to list all schemes and select the next one in the list.

**Comment by benweier** [comment]
Hey @bcrotty Do you have multiple schemes with the same filename installed? Schemr searches the list of available schemes for the currently active scheme (to work around behaviour for the Sublime Linter and Color Highlighter packages) by using the filename instead of the full path, and this causes it to get hung up on schemes with the same filename.

**Comment by bcrotty** [comment]
They probably do have the same filenames as others, but these are all from and inside ".sublime-package" files that I installed using Package Control. Is there any workaround?

**Comment by benweier** [comment]
Unfortunately there's no workaround other than removing schemes with duplicate filenames. This is inconvenient since you've installed the schemes in a `.sublime-package` file through Package Control. Because a *lot* more people use [Sublime Linter](https://packagecontrol.io/packages/SublimeLinter) and [Color Highlighter](https://packagecontrol.io/packages/Color%20Highlighter) packages than [Schemr](https://packagecontrol.io/packages/Schemr), I thought it would be more responsible to work with their limitations instead.

I'm considering a fix that should work for most use-cases, and I may reach out to the Linter and Highlighter authors for additional support.
