### ISSUE TITLE
list_schemes (CMD + F5) stopped working

### ISSUE THREAD

**Issue by mustafawm** [benweier/Schemr#33]
Hello,

ST v3 (build 3114) on OS X 10.11.6

Schemr's list_schemes was working fine but suddenly it is **not**!

I have the following in my keymap-user:
`{"keys": ["super+f5"], "command": "schemr_list_schemes"},`

Even running the `schemr_list_schemes` directly returns nothing!
 _the `next` & `previous` are still functioning though!_

Any thoughts?

**Comment by benweier** [comment]
Hi @mustafawm I'll take a look into this issue tonight. Meanwhile have you installed any new packages recently that may be using the same keybinding? Are there any errors displayed in the console <kbd>ctrl+`</kbd> after you try listing schemes?

**Comment by mustafawm** [comment]
Hi @benweier thanks for your timely response. 
I'm using Material theme which updates like 6 times/week!! (no kidding), and as you expected, I am getting the following material-theme-related error in console (upon `cmd+f5`): 
```
Error parsing Packages/Material Theme/schemes/OLD/Material-Theme.tmTheme
Error parsing Packages/User/Color Highlighter/themes/Material-Theme.tmTheme
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 553, in run_
    return self.run()
  File "schemr in /Users/mustafaal-saegh/Library/Application Support/Sublime Text 3/Installed Packages/Schemr.sublime-package", line 247, in run
  File "schemr in /Users/mustafaal-saegh/Library/Application Support/Sublime Text 3/Installed Packages/Schemr.sublime-package", line 99, in list_schemes
  File "schemr in /Users/mustafaal-saegh/Library/Application Support/Sublime Text 3/Installed Packages/Schemr.sublime-package", line 207, in parse_scheme
  File "schemr in /Users/mustafaal-saegh/Library/Application Support/Sublime Text 3/Installed Packages/Schemr.sublime-package", line 207, in <listcomp>
ValueError: invalid literal for int() with base 16: '<%'
```
And possible workarounds?

**Comment by benweier** [comment]
Thanks @mustafawm I use Material Theme myself and it is an excellent theme+scheme!

I can confirm the issue is being caused by Schemr trying to load [material-theme/.src/schemes/scheme.tmTheme](https://github.com/equinusocio/material-theme/blob/master/.src/schemes/scheme.tmTheme#L21) - a template file that @equinusocio uses to compile the different schemes packaged with Material Theme.

`&lt;%= scheme.background %&gt;` is not considered a valid colour value so the base 16 conversion fails. I will add some additional error checking to fix this. A temporary workaround is to add `"schemr_brightness_flags": false` to your settings.

**Comment by mustafawm** [comment]
Hi @benweier 
I know, it's the best theme/scheme out there. 

Thanks for the work around, it's working now 👍

**Comment by benweier** [comment]
@mustafawm this update should hit Package Control in the next hour or so.

This issue was [also reported](https://github.com/equinusocio/material-theme/issues/966) in Material Theme and I've requested the template file extension to be renamed so that Sublime and Schemr don't consider it a valid scheme option.

**Comment by mustafawm** [comment]
@benweier  That was fast, thanks man. I will remove the `"schemr_brightness_flags": false` then.
