### ISSUE TITLE
[Feature request] StThemr

### ISSUE THREAD

**Issue by Kristinita** [benweier/Schemr#35]
Many settings for elements in panels and concoles in Sublime Text is situated in [`stTheme` files](http://stackoverflow.com/a/10770137/5951529). Could you make a plugin that would allow a choice between `stTheme` files, which would work on the same principle as the Themr and Schemr?

Thanks.

**Comment by benweier** [comment]
Thanks @Kristinita it looks like `.stTheme` files are compatible with the `color_scheme` setting. I'll look into adding support for `.stTheme` on top of `.tmTheme` files.

**Comment by benweier** [comment]
I've investigated `.stTheme` files a bit further and the way they are used in `Widget.sublime-settings` files. Because the `color_scheme` setting is used for both the code editor view and the panel views (console, command palette, etc) it's not as simple as I initially assumed.

I don't think this feature is a good fit for "Schemr" as it would add quite a bit of code bloat that I'd rather not force upon Schemr users. Any new plugin to handle this functionality would have to write a new widget file to the filesystem for the current `theme` setting: i.e. `Widget - [theme].sublime-settings` => `Widget - Material-Theme-Darker.sublime-settings`. When the `theme` setting changes the Widget file would have to be renamed to match.

This approach isn't ideal because it doesn't scale for all of the widget settings that can be controlled independently to the editor settings (font sizes, line spacing, etc). I'll try playing around with a couple different concepts for how to achieve this.
